### ISSUE TITLE
Using Sylvester A.multiply is not a function

### ISSUE THREAD

**Issue by dnalrehtus** [infusion/Kalman.js#3]
I have been been trying to use Kalman.js in a simple node application, but I struggling to resolve the error 'TypeError: Cannot read property 'multiply' of undefined'.  I am using Sylvester.  I have looked at issue #1 which used math and part of the resolution was a recommendation to use Sylvester.

I rewrote the math code using Sylvester and it gives the same error about A.multipy.

My adapted code is from issue 1 is:

const Kalman = require('kalman');
const sylvester = require('sylvester');

let valx = [ 4, 5 ];
let valp = $M([[ 5, 0 ], [ 0, 4 ]]);

var valr = [];
var vala = $M([[ 5, 0 ], [ 0, 4 ]]);
valr['A'] = vala;

let kf = new Kalman.KF(valx, valp);
kf.update(valr);

Running this gives: TypeError: Cannot read property 'multiply' of undefined
    at KF.update (C:\Users\david\source\repos\sharesApr2020\NodeJS\nodeApp\node_modules\kalman\kalman.js:75:36).

I am probably missing something simple. Do you have any suggestions?

**Comment by infusion** [comment]
You forgot to set matrix B, even if you don't need it in your design, pass the zero matrix.

**Comment by infusion** [comment]
For a simple example, have a look here:
https://github.com/infusion/GPS.js/blob/master/examples/maps/server.js

**Comment by dnalrehtus** [comment]
Thank you for your response.

I made an incorrect assumption from the typescript error about the use of
multiply and from issue #1 and I mistakenly thought that it was a Sylvester
issue. Following your helpful response I see that Kalman and Sylvester both
work perfectly.  My mistake was as you said, it was a missing matrix. The
GPS example is excellent.

dnalrehtus

**Comment by infusion** [comment]
Glad it works now :)
